# Generated by Django 3.0.3 on 2020-04-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
